-- CreateTable
CREATE TABLE "casos" (
    "id" TEXT NOT NULL,
    "numero" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "pregunta" TEXT NOT NULL,
    "eje" TEXT NOT NULL,
    "indicio" TEXT NOT NULL,
    "periodo" TEXT NOT NULL,
    "ambito" TEXT NOT NULL,
    "estado" TEXT NOT NULL,
    "contexto" TEXT NOT NULL,
    "pregunta_investigacion" TEXT NOT NULL,
    "lamina" JSONB NOT NULL,
    "evidencias" JSONB NOT NULL,
    "analisis" TEXT NOT NULL,
    "aprendizaje" TEXT NOT NULL,
    "que_cambio" TEXT NOT NULL,
    "produccion_relacionada" JSONB NOT NULL,
    "es_demo" BOOLEAN NOT NULL DEFAULT false,
    "aclaracion" TEXT,
    "publicado_en" TIMESTAMP(3),
    "publicado_por" TEXT,
    "borrador" JSONB,
    "borrador_en" TIMESTAMP(3),
    "borrador_por" TEXT,

    CONSTRAINT "casos_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "casos_numero_key" ON "casos"("numero");

-- CreateIndex
CREATE UNIQUE INDEX "casos_slug_key" ON "casos"("slug");

-- Los cuatro casos de hoy (work/casos-aliados-fotos/SPEC.md §4), publicados y
-- sin `publicado_por`: los cargó la migración, no una persona. Son siempre
-- cuatro y no se crean desde el admin, así que sin esto la tabla no tendría
-- casos que editar.
--
-- De qué salió y cómo se generó (resguardo 3 del padre, DECISIONS): un
-- script que no se commitea leyó features/investigacion/data/casos.ts, que se
-- borra en el mismo PR, pasó cada caso al documento de `esquemaCaso` y lo
-- validó con ese esquema antes de escribir la fila: la ficha técnica en sus
-- tres columnas, la lámina con su foto centrada, y cada evidencia sin su id
-- ni su rótulo, que salen de su posición (el script frenaba si algún rótulo
-- no era «EVIDENCIA 0N» en orden). El tinte de cada carpeta no entra: va por
-- número, en código. La aclaración vacía queda nula.
INSERT INTO "casos" ("id", "numero", "slug", "pregunta", "eje", "indicio", "periodo", "ambito", "estado", "contexto", "pregunta_investigacion", "lamina", "evidencias", "analisis", "aprendizaje", "que_cambio", "produccion_relacionada", "es_demo", "aclaracion", "publicado_en") VALUES
  ('caso-01', '01', 'oaxaca-transformacion-colectiva', '¿Qué pasa cuando una generación docente problematiza durante dos años la matemática que enseña?', 'Empoderamiento y desarrollo profesional docente', 'De cursar la maestría a tutorear la siguiente', '2011 — 2013', 'Oaxaca, México · Secundaria', 'CERRADO', 'Veintiocho profesoras y profesores de secundaria cursan la Maestría en la Enseñanza de las Matemáticas en la Educación Secundaria del Instituto Estatal de Educación Pública de Oaxaca. Cuatrocientas ochenta horas institucionales, en encuentros de fin de semana, donde se problematizan lo trigonométrico, lo proporcional, lo exponencial, lo geométrico y lo variacional.', '¿Cómo se transforma la relación de un cuerpo docente con el saber matemático cuando la intervención parte de potenciar sus fortalezas y no de señalar sus carencias?', '{"foto":{"src":"/investigacion/caso-01-lamina.webp","alt":"Ilustración de un equipo docente analizando una tarea de geometría alrededor de una mesa de trabajo","foco":{"x":0.5,"y":0.5}},"sujecion":"clip","rotulo":"LÁMINA 01 · SEMINARIO DE PROBLEMATIZACIÓN"}'::jsonb, '[{"titulo":"SEMINARIOS DE PROBLEMATIZACIÓN","descripcion":"Cuarenta horas reloj por saber; alguno se extendió a ochenta.","movible":true},{"titulo":"REGISTRO DE TUTORÍAS","descripcion":"Ocho episodios de trabajo con la segunda generación, unas cien horas.","movible":true},{"titulo":"DISEÑO: COLOR Y PROPORCIÓN","descripcion":"Rebeca funde matemática y arte con los colores primarios y secundarios.","movible":true},{"titulo":"DISEÑO: LA JÍCARA","descripcion":"Rigoberto Díaz construye volumen y capacidad desde una unidad de medida propia.","movible":true},{"titulo":"DISEÑO: EL PAPALOTE","descripcion":"Isabel Sánchez explicita el pensamiento trigonométrico de algo que ya hacía en clase.","movible":false}]'::jsonb, 'El dispositivo no lleva una propuesta para aplicar: pone el saber matemático en discusión y deja que cada docente diseñe desde su contexto. Por eso los diseños que salen no se parecen entre sí — una jícara, un papalote, una paleta de colores— y sin embargo todos problematizan lo mismo.', 'El acompañamiento no termina con el curso: ahí recién empieza.', 'Dos docentes de la primera generación pasaron a tutorear la segunda. Algunos convirtieron sus diseños en tesis; la mayoría transformó su práctica y sigue en contacto con la comunidad.', '[{"titulo":"Reyes-Gasperini (2016) · Perfiles Educativos","href":"/biblioteca"},{"titulo":"Empoderamiento docente y Socioepistemología (Gedisa)","href":"/biblioteca"}]'::jsonb, false, NULL, CURRENT_TIMESTAMP),
  ('caso-02', '02', 'resignificacion-escuelas-tecnicas', '¿Cómo cambia la relación de una docente con el saber que enseña, ciclo tras ciclo?', 'Resignificación del conocimiento matemático', 'Vivir la tarea antes de darla', '2025', 'Escuelas técnicas · Argentina, México, Brasil y Colombia', 'EN CURSO', 'Un programa sostenido con docentes en servicio de escuelas técnicas públicas de cuatro países. Cada ciclo revisa un pensamiento matemático y dura entre tres y cinco meses: primero el cuerpo docente atraviesa las tareas, después las lleva al aula y por último analiza en conjunto lo que ocurrió.', '¿Cómo se configura la resignificación del conocimiento matemático escolar en un espacio sostenido de desarrollo profesional docente?', '{"foto":{"src":"/investigacion/caso-03-lamina.webp","alt":"Ilustración de una carpeta de anillas con esquemas de geometría y una docente pensando en conexiones","foco":{"x":0.5,"y":0.5}},"sujecion":"esquinas","rotulo":"LÁMINA 02 · GUÍA DE TAREAS DISRUPTIVAS"}'::jsonb, '[{"titulo":"GUÍA DE TAREAS DISRUPTIVAS","descripcion":"Entre siete y diez tareas por año escolar, en dos versiones.","movible":true},{"titulo":"VERSIÓN DOCENTE","descripcion":"Intencionalidad didáctica, estrategias posibles, errores esperados y bibliografía.","movible":true},{"titulo":"PRE-TEST Y CIERRE","descripcion":"Cinco preguntas al abrir y cinco al cerrar, que se confrontan.","movible":true},{"titulo":"EPISODIO ALGEBRAICO","descripcion":"Una experiencia de secundaria en Argentina.","movible":true},{"titulo":"EPISODIO GEOMÉTRICO","descripcion":"Una experiencia de secundaria en Colombia.","movible":false}]'::jsonb, 'Los indicadores rastrean tres cosas distintas: cuándo hay confrontación, cuándo hay resignificación y cuándo cambia de verdad la relación con el saber. Lo epistémico aparece con fuerza en la fase experiencial; lo didáctico se consolida recién en las que siguen.', 'Resignificar no es un estado al que se llega: es lo que se vuelve a andar cada ciclo.', 'El conocimiento matemático escolar pasa a ser objeto de discusión profesional dentro del espacio de formación, y los resultados de cada ciclo sostienen las decisiones del siguiente.', '[{"titulo":"Reyes-Gasperini y Gómez-Osalde (2025) · RELIME","href":"/biblioteca"}]'::jsonb, false, NULL, CURRENT_TIMESTAMP),
  ('caso-03', '03', 'evaluacion-mas-alla-del-puntaje', '¿Qué nos dice una evaluación más allá del puntaje?', 'Evaluación y evidencia educativa', 'Lo que un 72 no cuenta', '2023 — 2024', 'Escuela secundaria', 'EN CURSO', 'Un equipo necesita leer resultados de aprendizaje sin reducir la experiencia educativa a una cifra aislada.', '¿Qué evidencias permiten comprender estrategias, dificultades y formas de razonamiento detrás de un resultado?', '{"foto":{"src":"/investigacion/caso-02-lamina.webp","alt":"Ilustración de una planilla de evaluación integral anotada a mano, con gráficos, notas y una lapicera","foco":{"x":0.5,"y":0.5}},"sujecion":"cinta","rotulo":"LÁMINA 03 · LECTURA DE RESULTADOS"}'::jsonb, '[{"titulo":"INSTRUMENTO DE EVALUACIÓN","descripcion":"Fragmento del instrumento y sus consignas.","movible":true},{"titulo":"RESPUESTAS SELECCIONADAS","descripcion":"Estrategias, errores y razonamientos que asoman.","movible":true},{"titulo":"COMPARACIÓN DE ESTRATEGIAS","descripcion":"Caminos distintos hacia una misma respuesta.","movible":true},{"titulo":"NOTA DE INTERPRETACIÓN","descripcion":"Qué dicen los resultados leídos en contexto.","movible":false}]'::jsonb, 'Los mismos puntajes esconden recorridos distintos: al mirar respuestas, estrategias y errores aparece información que la cifra final no muestra.', 'El progreso es más que un número.', 'La evaluación deja de funcionar como cierre y empieza a orientar nuevas decisiones pedagógicas.', '[{"titulo":"Marco de evaluación (placeholder)","href":"/biblioteca"}]'::jsonb, false, 'Simulación editorial para probar la estructura. No representa todavía un proyecto específico de Empoderamiento Docente.', CURRENT_TIMESTAMP),
  ('caso-04', '04', 'contenido-curricular-herramienta-pensamiento', '¿Cómo puede un contenido curricular convertirse en una herramienta de pensamiento?', 'Currículum y pensamiento matemático', 'Del listado de temas al mapa de relaciones', '2024 — 2025', 'Equipo curricular', 'EN CURSO', 'Una revisión curricular busca conectar contenidos, prácticas y progresiones con formas de actuar matemáticamente.', '¿Cómo organizar una progresión que no se limite a enumerar contenidos y permita desarrollar estrategias, argumentación y toma de decisiones?', '{"foto":{"src":"/investigacion/caso-01-lamina.webp","alt":"Ilustración de un equipo docente analizando una tarea de geometría alrededor de una mesa de trabajo","foco":{"x":0.5,"y":0.5}},"sujecion":"esquinas","rotulo":"LÁMINA 04 · MAPA DE PROGRESIONES"}'::jsonb, '[{"titulo":"MAPA CURRICULAR INICIAL","descripcion":"La organización vigente de contenidos.","movible":true},{"titulo":"ANÁLISIS DE PROGRESIONES","descripcion":"Cómo progresan las ideas entre grados y ciclos.","movible":true},{"titulo":"SITUACIONES DE APRENDIZAJE","descripcion":"Situaciones diseñadas para habilitar debate.","movible":true},{"titulo":"COMPARACIÓN DE FORMULACIONES","descripcion":"Una misma idea, formulada de dos maneras.","movible":true},{"titulo":"REGISTRO DE DECISIONES","descripcion":"Decisiones del equipo y sus fundamentos.","movible":true},{"titulo":"MATERIAL PARA DOCENTES","descripcion":"Orientaciones de trabajo para el aula.","movible":false},{"titulo":"MATERIAL PARA ESTUDIANTES","descripcion":"Actividades y tareas del recorrido.","movible":false},{"titulo":"SÍNTESIS DE HALLAZGOS","descripcion":"Qué aprendió el equipo en el proceso.","movible":false},{"titulo":"RECORRIDO AJUSTADO","descripcion":"La progresión final, lista para implementarse.","movible":false}]'::jsonb, 'Al contrastar el mapa inicial con situaciones de aula, la secuencia temática queda corta: las decisiones reales piden relaciones entre contenidos, prácticas y problemas — no listas.', 'Una progresión potente conecta contenidos con problemas reales.', 'Los contenidos se reorganizan en torno a relaciones, prácticas y escenarios de aprendizaje.', '[{"titulo":"Guía curricular (placeholder)","href":"/biblioteca"},{"titulo":"Situaciones de aprendizaje (placeholder)","href":"/biblioteca"}]'::jsonb, false, 'Simulación editorial para probar la estructura. No representa todavía un proyecto específico de Empoderamiento Docente.', CURRENT_TIMESTAMP);
